// ----------------------------------------------------------------------------------
// Module Name: input_controller.v
// Description: Debounces all asynchronous button inputs and generates pulses for 
// game controls.
// ----------------------------------------------------------------------------------

module input_controller #(parameter integer DEBOUNCE_TICKS = 250_000,
                          parameter integer SOFT_REPEAT_TICKS = 2_500_000)
                         (input wire i_clk,
                          input wire i_rst,
                          input wire i_btn_left,
                          input wire i_btn_right,
                          input wire i_btn_rotate,
                          input wire i_btn_soft,
                          input wire i_btn_hard,
                          input wire i_btn_swap,
                          input wire i_btn_pause,
                          output reg o_left_pulse,
                          output reg o_right_pulse,
                          output reg o_rotate_pulse,
                          output reg o_soft_pulse,
                          output reg o_hard_pulse,
                          output reg o_swap_pulse,
                          output reg o_pause_pulse,
                          output wire o_soft_down,
                          output wire o_hard_down);
    
    localparam integer SOFT_REPEAT_RELOAD = (SOFT_REPEAT_TICKS > 1) ? (SOFT_REPEAT_TICKS - 1) : 0;
    
    // Debounced button levels generated by the per-button debouncer instances
    wire left_db, right_db, rotate_db, soft_db, hard_db, swap_db, pause_db;
    
    // Previous states of debounced levels
    reg  left_db_d, right_db_d, rotate_db_d, soft_db_d, hard_db_d, swap_db_d, pause_db_d;
    reg [31:0] soft_repeat_cnt;
    
    // Synchronizers + mechanical debounce for each button
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_left (
    .i_clk(i_clk), .i_button(i_btn_left), .i_rst(i_rst), .o_button(left_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_right (
    .i_clk(i_clk), .i_button(i_btn_right), .i_rst(i_rst), .o_button(right_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_rotate (
    .i_clk(i_clk), .i_button(i_btn_rotate), .i_rst(i_rst), .o_button(rotate_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_soft (
    .i_clk(i_clk), .i_button(i_btn_soft), .i_rst(i_rst), .o_button(soft_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_hard (
    .i_clk(i_clk), .i_button(i_btn_hard), .i_rst(i_rst), .o_button(hard_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_swap (
    .i_clk(i_clk), .i_button(i_btn_swap), .i_rst(i_rst), .o_button(swap_db)
    );
    debouncer #(.DEBOUNCE_TICKS(DEBOUNCE_TICKS)) db_pause (
    .i_clk(i_clk), .i_button(i_btn_pause), .i_rst(i_rst), .o_button(pause_db)
    );

    assign o_soft_down = soft_db;
    assign o_hard_down = hard_db;
    
    // Turn stable levels into edge pulses and auto-repeat signals
    always @(posedge i_clk or posedge i_rst) begin
        if (i_rst) begin
            {left_db_d, right_db_d, rotate_db_d, soft_db_d, hard_db_d, swap_db_d, pause_db_d} <= 7'b0;
            o_pause_pulse                                                         <= 1'b0;
            o_left_pulse                                                          <= 1'b0;
            o_right_pulse                                                         <= 1'b0;
            o_rotate_pulse                                                        <= 1'b0;
            o_soft_pulse                                                          <= 1'b0;
            o_hard_pulse                                                          <= 1'b0;
            o_swap_pulse                                                          <= 1'b0;
            soft_repeat_cnt                                                       <= SOFT_REPEAT_RELOAD;
        end
        
        else begin
            // This ensures that holding the button only triggers the action once, while
            // downstream logic sees a single tick instead of a stream of repeats.
            o_left_pulse   <= left_db  & ~left_db_d;
            o_right_pulse  <= right_db & ~right_db_d;
            o_rotate_pulse <= rotate_db & ~rotate_db_d;
            o_hard_pulse   <= hard_db  & ~hard_db_d;
            o_swap_pulse   <= swap_db  & ~swap_db_d;
            o_pause_pulse  <= pause_db & ~pause_db_d;
            
            o_soft_pulse <= 1'b0;
            if (soft_db  & ~soft_db_d) begin
                o_soft_pulse    <= 1'b1;
                soft_repeat_cnt <= SOFT_REPEAT_RELOAD;
            end 
            
            else if (soft_db) begin
                // Soft drop is the only control allowed to repeat while held,
                // implemented with a auto-repeat counter.
                if (SOFT_REPEAT_TICKS <= 1) begin
                    o_soft_pulse    <= 1'b1;
                    soft_repeat_cnt <= SOFT_REPEAT_RELOAD;
                end

                else if (soft_repeat_cnt == 0) begin
                    o_soft_pulse    <= 1'b1;
                    soft_repeat_cnt <= SOFT_REPEAT_RELOAD;
                end
                
                else begin
                    soft_repeat_cnt <= soft_repeat_cnt - 1'b1;
                end
            end

            else begin
                soft_repeat_cnt <= SOFT_REPEAT_RELOAD;
            end
            
            // Capture current debounced levels for next-cycle edge detection
            left_db_d   <= left_db;
            right_db_d  <= right_db;
            rotate_db_d <= rotate_db;
            soft_db_d   <= soft_db;
            hard_db_d   <= hard_db;
            swap_db_d   <= swap_db;
            pause_db_d  <= pause_db;
        end
    end
endmodule
    
